### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by er1c** [scalacenter/scoop-bloop#8]
```
Running installer script...
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading C:\Users\eric\scoop\apps\bloop\1.4.3:latest.release
  not found: C:\Users\eric\.ivy2\local\C\Users\eric\scoop\apps\bloop\1.4.3
  not found: https://repo1.maven.org/maven2/C/\Users\eric\scoop\apps\bloop\1.4.3/maven-metadata.xml
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:331)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:273)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:329)
        at coursier.Resolve.validate0$1(Resolve.scala:114)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:158)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Linking ~\scoop\apps\bloop\current => ~\scoop\apps\bloop\1.4.3
Creating shim for 'bloop'.
Can't shim 'bloop': File doesn't exist.
```

**Comment by PAStheLoD** [comment]
Hello,

I've encountered the same problem with bloop 1.4.4, when upgrading from 1.4.0-RC1.

Doing a `scoop uninstall bloop && scoop install bloop` does not help.
